### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by wuchong** [A-limon/pacman#3]
hello,I love your theme very much.  And I found that you start update your theme(that's great ). But, there are still some bugs or questions ,such as , the search box , and how to resize the post font size , and how to change duoshuo's theme .

**Comment by A-limon** [comment]
Thank you,I will appreciate if you can tell me more detail about the search box. 
you can modify `font-size` in `themes/pacman/source/_base/variable.styl` to change your blog's font size,and modify the file `themes/pacman/source/_partial/duoshuo.styl`to change duoshuo's style.

**Comment by wuchong** [comment]
@A-limon  thanks a lot. The theme can perform perfect in chrome .However in 360(v6.3) the  search box displays like this 
![image](https://f.cloud.github.com/assets/5378924/1960805/7be5e1f4-825b-11e3-883c-c674bc47de1a.png)

And in IE it will crash , although I do not use IE.

**Comment by wuchong** [comment]
@A-limon  I've fixed it with adding `-webkit-appearance textfield` to `.search input` in `header.styl` file.
In addition , if I want to add a [douban](http://www.douban.com) link on the footer  just like weibo,github..., how to do it?
![image](https://f.cloud.github.com/assets/5378924/1961140/6c2cce78-8268-11e3-8ef9-4be5e9abfae0.png)

**Comment by A-limon** [comment]
I'm glad to hear that you have solved the search box issue.I make this theme on OSX
,so I can't have a compatibility test on many other browsers,but I tested it on Chrome, Firefox, Safari,iOS and Android.
I use [fontawesome](http://fontawesome.io/icons/) to display icons in Pacman,but it's seem that they don't have any icon for douban, so you can use other vector icons or background picture instead of fontawesome.

**Comment by wuchong** [comment]
thanks , all of the problems have been solved .  I use [fontdiao](https://github.com/lexrus/fontdiao) to display douban. Welcome to visit my [blog](http://wuchong.me) .
